import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from '../ui/node_modules/typescript/lib/typescript.js';
import { EVENTS } from '../shared/events.js';
const compile = (source) => 'data:text/javascript;base64,' + Buffer.from(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText).toString('base64');
const thread = compile(readFileSync(new URL('../ui/src/thread/thread.ts', import.meta.url), 'utf8'));
const source = readFileSync(new URL('../ui/src/thread/stream.ts', import.meta.url), 'utf8').replace("'@shared/events'", JSON.stringify(new URL('../shared/events.js', import.meta.url).href)).replace("'./thread'", JSON.stringify(thread));
const { setupStream } = await import(compile(source));
test('完成时保留全部历史、行对象和 key，最终正文原地校准且无历史请求', () => {
    const older = { key: 'older', kind: 'user', content: '早期历史' };
    const rows = [older]; let busy = true;
    const stream = setupStream({ thread: 'a', getRows: () => rows, pushRow: (row) => (rows.push(row), row), setBusy: (value) => busy = value, bump() {}, refresh() { assert.fail('不得刷新历史'); } });
    const emit = (type, data = {}) => stream.onEvent(type, { thread: 'a', ...data });
    emit(EVENTS.DELTA, { content: '部分正文' });
    const live = rows[1], key = live.key;
    emit(EVENTS.TEXT_DONE, { kind: 'message', content: '完整正文' });
    emit(EVENTS.DONE);
    assert.equal(rows.length, 2);
    assert.equal(rows[0], older);
    assert.equal(rows[1], live);
    assert.equal(live.key, key);
    assert.equal(live.content, '完整正文');
    assert.equal(live.streaming, false);
    assert.equal(busy, false);
    emit(EVENTS.TEXT_DONE, { kind: 'message', content: '没有增量也显示' });
    emit(EVENTS.DONE);
    assert.equal(rows[2].content, '没有增量也显示');
});
